import { describe, expect, it, beforeEach } from 'vitest';
import Database from 'better-sqlite3';
import { migrate } from '../src/database/schema.js';
import { seedItems } from '../src/database/seed.js';
import { YouthExchangeService } from '../src/services/coreService.js';
import { saleUnitPrice } from '../src/utils/money.js';
let db:any, svc:YouthExchangeService, eventId:number;
beforeEach(()=>{ db=new Database(':memory:'); db.pragma('foreign_keys=ON'); migrate(db); seedItems(db); svc=new YouthExchangeService(db); eventId=svc.createEvent({guildId:'g',name:'테스트',channelId:'c'}); svc.addParticipant(eventId,'u1'); svc.addParticipant(eventId,'u2'); });
describe('기본금 및 관리자 자금',()=>{ it('전체 기본금 지급, 중복 방지, 중복 허용',()=>{ expect(svc.grantStartingFund(eventId,'a',['u1','u2'],15000,false).paid).toBe(2); expect(svc.grantStartingFund(eventId,'a',['u1','u2'],15000,false).skipped).toBe(2); expect(svc.grantStartingFund(eventId,'a',['u1'],15000,true).paid).toBe(1); expect(db.prepare('SELECT balance FROM participants WHERE user_id=?').get('u1').balance).toBe(30000); });
 it('특정 유저 자동 등록 기본금과 추가 자금, 감사 기록',()=>{ svc.grantStartingFund(eventId,'a',['u3'],10000,false); expect(db.prepare('SELECT balance FROM participants WHERE user_id=?').get('u3').balance).toBe(10000); svc.grantAdminFund(eventId,'a','u3',5000,'보너스'); svc.grantAdminFund(eventId,'a','u3',1000,'보너스2'); expect(db.prepare('SELECT balance FROM participants WHERE user_id=?').get('u3').balance).toBe(16000); expect(db.prepare('SELECT COUNT(*) c FROM transactions').get().c).toBe(3); expect(db.prepare('SELECT COUNT(*) c FROM admin_audit_logs').get().c).toBe(3); });
 it('잘못된 지급과 종료 이벤트 지급 차단',()=>{ expect(()=>svc.grantAdminFund(eventId,'a','u1',0,'x')).toThrow(); expect(()=>svc.grantAdminFund(eventId,'a','missing',1,'x')).toThrow(); svc.endEvent(eventId,'a'); expect(()=>svc.grantAdminFund(eventId,'a','u1',1,'x')).toThrow(); }); });
describe('구매',()=>{ it('공개 아이템 구매 및 비공개/잔액/수량 차단',()=>{ svc.grantStartingFund(eventId,'a',['u1'],15000); svc.setItemPublic(eventId,'a',[1],true); svc.startBuying(eventId); expect(()=>svc.purchase(eventId,'u1',2,1)).toThrow(); expect(()=>svc.purchase(eventId,'u1',1,0)).toThrow(); const r=svc.purchase(eventId,'u1',1,2); expect(r.balance).toBe(9000); expect(()=>svc.purchase(eventId,'u1',1,99)).toThrow(); }); });
describe('매입금 및 계절',()=>{ it('개별/등급 매입금과 최소 검증, 공개 후 수정 차단, 계절 입력',()=>{ svc.grantStartingFund(eventId,'a',['u1'],15000); svc.setItemPublic(eventId,'a',[1],true); svc.startBuying(eventId); svc.purchase(eventId,'u1',1,2); svc.closeBuying(eventId); expect(()=>svc.setBuyout(eventId,'a',1,1)).toThrow(); svc.setBuyout(eventId,'a',1,6000); svc.setTierBuyout(eventId,'a','중가',0); svc.setTierBuyout(eventId,'a','고가',0); svc.setBuyout(eventId,'a',4,0); svc.setBuyout(eventId,'a',7,0); svc.setBuyout(eventId,'a',10,0); expect(()=>svc.setSeason(eventId,'a','봄' as any)).toThrow(); [2,3,5,6,8,9,11,12].forEach(id=>svc.setBuyout(eventId,'a',id,0)); svc.publishBuyouts(eventId,'a'); expect(()=>svc.setBuyout(eventId,'a',1,6000)).toThrow(); for(const s of ['봄','여름','가을','겨울'] as const){ const id=svc.createEvent({guildId:'g'+s,name:s,channelId:'c'}); for(let item=1;item<=12;item++) svc.setBuyout(id,'a',item,0); svc.publishBuyouts(id,'a'); svc.setSeason(id,'a',s); expect(db.prepare('SELECT selected_season FROM events WHERE event_id=?').get(id).selected_season).toBe(s); } }); });
describe('판매와 정산',()=>{ function prep(){ svc.grantStartingFund(eventId,'a',['u1','u2'],50000); svc.setItemPublic(eventId,'a',[1],true); svc.startBuying(eventId); svc.purchase(eventId,'u1',1,2); svc.purchase(eventId,'u2',1,1); svc.closeBuying(eventId); for(let i=1;i<=12;i++) svc.setBuyout(eventId,'a',i,i===1?300000:0); svc.publishBuyouts(eventId,'a'); svc.setSeason(eventId,'a','봄'); svc.startSelling(eventId,'a',{minutes:5}); }
 it('선택 계절 판매, 변경, 취소, 초과 차단, 종료 후 차단',()=>{ prep(); svc.saleRequest(eventId,'u1',1,2); svc.saleRequest(eventId,'u1',1,1); expect(()=>svc.saleRequest(eventId,'u1',4,1)).toThrow(); expect(()=>svc.saleRequest(eventId,'u1',1,9)).toThrow(); svc.cancelSale(eventId,'u1',1); svc.saleRequest(eventId,'u2',1,1); svc.closeSelling(eventId); expect(()=>svc.saleRequest(eventId,'u2',1,1)).toThrow(); });
 it('가격 계산, 미리보기 무변경, 정산, 중복 정산 방지',()=>{ prep(); svc.saleRequest(eventId,'u1',1,2); svc.saleRequest(eventId,'u2',1,1); svc.closeSelling(eventId); expect(saleUnitPrice(39500,3)).toBe(13000); const pre=svc.previewSettlement(eventId).find((r:any)=>r.item_id===1); expect(pre.unit_price).toBe(100000); expect(db.prepare('SELECT balance FROM participants WHERE user_id=?').get('u1').balance).toBe(44000); svc.settle(eventId,'a'); expect(db.prepare('SELECT quantity FROM inventories WHERE user_id=? AND item_id=1').get('u1').quantity).toBe(0); expect(db.prepare('SELECT balance FROM participants WHERE user_id=?').get('u1').balance).toBe(244000); expect(()=>svc.settle(eventId,'a')).toThrow(); }); });
describe('라운드 및 종료/배포',()=>{ it('다음 라운드 유지와 종료 소멸',()=>{ svc.grantStartingFund(eventId,'a',['u1'],50000); svc.setItemPublic(eventId,'a',[1],true); svc.startBuying(eventId); svc.purchase(eventId,'u1',1,1); svc.closeBuying(eventId); for(let i=1;i<=12;i++) svc.setBuyout(eventId,'a',i,i===1?3000:0); svc.publishBuyouts(eventId,'a'); svc.setSeason(eventId,'a','봄'); svc.startSelling(eventId,'a',{minutes:5}); svc.closeSelling(eventId); svc.settle(eventId,'a'); svc.nextRound(eventId,'a'); expect(db.prepare('SELECT current_round,status FROM events WHERE event_id=?').get(eventId).status).toBe('BUYOUT_SETTING'); expect(()=>svc.startBuying(eventId)).toThrow(); svc.endEvent(eventId,'a'); expect(db.prepare('SELECT quantity FROM inventories WHERE event_id=?').get(eventId).quantity).toBe(0); }); });
