import { SlashCommandBuilder, ChannelType, ActionRowBuilder, ButtonBuilder, ButtonStyle } from 'discord.js';
import { PRICE_TIERS, SEASONS } from '../../config/items.js';
export const command = new SlashCommandBuilder().setName('계절투자').setDescription('청춘거래소 이벤트 명령어')
.addSubcommand((s:any)=>s.setName('이벤트생성').setDescription('청춘거래소 이벤트 생성').addStringOption((o:any)=>o.setName('이름').setDescription('이벤트 이름').setRequired(true)).addChannelOption((o:any)=>o.setName('채널').setDescription('진행 채널').addChannelTypes(ChannelType.GuildText).setRequired(true)).addRoleOption((o:any)=>o.setName('참가역할').setDescription('참가 역할').setRequired(false)).addIntegerOption((o:any)=>o.setName('기본금').setDescription('기본금').setMinValue(1)))
.addSubcommand((s:any)=>s.setName('기본금지급').setDescription('기본금 지급').addStringOption((o:any)=>o.setName('대상유형').setDescription('대상').setRequired(true).addChoices({name:'전체',value:'전체'},{name:'역할',value:'역할'},{name:'유저',value:'유저'})).addRoleOption((o:any)=>o.setName('역할').setDescription('대상 역할')).addUserOption((o:any)=>o.setName('유저').setDescription('대상 유저')).addIntegerOption((o:any)=>o.setName('금액').setDescription('금액').setMinValue(1)).addBooleanOption((o:any)=>o.setName('중복허용').setDescription('중복 지급 허용')))
.addSubcommand((s:any)=>s.setName('자금지급').setDescription('관리자 추가 자금 지급').addUserOption((o:any)=>o.setName('유저').setDescription('대상').setRequired(true)).addIntegerOption((o:any)=>o.setName('금액').setDescription('금액').setRequired(true).setMinValue(1)).addStringOption((o:any)=>o.setName('사유').setDescription('사유').setRequired(true)))
.addSubcommand((s:any)=>s.setName('아이템공개').setDescription('아이템 공개').addStringOption((o:any)=>o.setName('아이템id목록').setDescription('예: 1,2,3').setRequired(true)))
.addSubcommand((s:any)=>s.setName('아이템비공개').setDescription('아이템 비공개').addStringOption((o:any)=>o.setName('아이템id목록').setDescription('예: 1,2,3').setRequired(true)))
.addSubcommand((s:any)=>s.setName('구매시작').setDescription('구매 시작')).addSubcommand((s:any)=>s.setName('구매종료').setDescription('구매 종료'))
.addSubcommand((s:any)=>s.setName('매입금설정').setDescription('개별 매입금 설정').addIntegerOption((o:any)=>o.setName('아이템id').setDescription('아이템 ID').setRequired(true)).addIntegerOption((o:any)=>o.setName('매입금').setDescription('매입금').setRequired(true).setMinValue(0)))
.addSubcommand((s:any)=>s.setName('등급매입금설정').setDescription('등급 매입금 설정').addStringOption((o:any)=>o.setName('등급').setDescription('가격 등급').setRequired(true).addChoices(...PRICE_TIERS.map(x=>({name:x,value:x})))).addIntegerOption((o:any)=>o.setName('매입금').setDescription('매입금').setRequired(true).setMinValue(0)))
.addSubcommand((s:any)=>s.setName('매입금확인').setDescription('매입금 확인')).addSubcommand((s:any)=>s.setName('매입금공개').setDescription('매입금 공개'))
.addSubcommand((s:any)=>s.setName('계절결과').setDescription('외부 계절 결과 입력').addStringOption((o:any)=>o.setName('계절').setDescription('계절').setRequired(true).addChoices(...SEASONS.map(x=>({name:x,value:x})))))
.addSubcommand((s:any)=>s.setName('판매시작').setDescription('판매 시작').addIntegerOption((o:any)=>o.setName('분').setDescription('판매 가능 시간(분)').setMinValue(1)).addStringOption((o:any)=>o.setName('종료시각').setDescription('HH:mm')))
.addSubcommand((s:any)=>s.setName('판매종료').setDescription('판매 종료')).addSubcommand((s:any)=>s.setName('정산미리보기').setDescription('정산 미리보기')).addSubcommand((s:any)=>s.setName('정산').setDescription('정산')).addSubcommand((s:any)=>s.setName('다음라운드').setDescription('다음 라운드')).addSubcommand((s:any)=>s.setName('이벤트종료').setDescription('이벤트 종료'))
.addSubcommand((s:any)=>s.setName('현황').setDescription('이벤트 현황')).addSubcommand((s:any)=>s.setName('상점').setDescription('상점')).addSubcommand((s:any)=>s.setName('구매').setDescription('아이템 구매').addIntegerOption((o:any)=>o.setName('아이템id').setDescription('아이템 ID').setRequired(true)).addIntegerOption((o:any)=>o.setName('수량').setDescription('수량').setRequired(true).setMinValue(1)))
.addSubcommand((s:any)=>s.setName('내정보').setDescription('내 정보')).addSubcommand((s:any)=>s.setName('판매신청').setDescription('판매 신청').addIntegerOption((o:any)=>o.setName('아이템id').setDescription('아이템 ID').setRequired(true)).addIntegerOption((o:any)=>o.setName('수량').setDescription('최종 수량').setRequired(true).setMinValue(1)))
.addSubcommand((s:any)=>s.setName('판매변경').setDescription('판매 변경').addIntegerOption((o:any)=>o.setName('아이템id').setDescription('아이템 ID').setRequired(true)).addIntegerOption((o:any)=>o.setName('수량').setDescription('최종 수량').setRequired(true).setMinValue(1)))
.addSubcommand((s:any)=>s.setName('판매취소').setDescription('판매 취소').addIntegerOption((o:any)=>o.setName('아이템id').setDescription('아이템 ID').setRequired(true))).addSubcommand((s:any)=>s.setName('내판매').setDescription('내 판매')).addSubcommand((s:any)=>s.setName('내역').setDescription('내 거래 내역'))
.addSubcommand((s:any)=>s.setName('판매현황').setDescription('관리자 판매 현황')).addSubcommand((s:any)=>s.setName('유저조회').setDescription('관리자 유저 조회').addUserOption((o:any)=>o.setName('유저').setDescription('조회 대상').setRequired(true))).addSubcommand((s:any)=>s.setName('관리기록').setDescription('관리자 감사 기록'));
export const confirmRow=(id:string)=>new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(id).setLabel('확인').setStyle(ButtonStyle.Danger));
