import { YouthExchangeService } from '../../services/coreService.js'; import { isAdminLike } from '../../utils/permissions.js'; import { formatWon } from '../../utils/money.js';
const adminSubs=new Set(['이벤트생성','기본금지급','자금지급','아이템공개','아이템비공개','구매시작','구매종료','매입금설정','등급매입금설정','매입금확인','매입금공개','계절결과','판매시작','판매종료','판매현황','정산미리보기','정산','다음라운드','이벤트종료','유저조회','관리기록']);
const ids=(s:string)=>s.split(',').map(x=>Number(x.trim())).filter(Number.isInteger);
export async function handleSeasonInvestment(interaction:any, svc:YouthExchangeService){ const sub=interaction.options.getSubcommand(); const guildId=interaction.guildId; const uid=interaction.user.id; try{ if(adminSubs.has(sub)&&!isAdminLike(interaction.member)) return interaction.reply({content:'관리자 권한이 필요합니다.',ephemeral:true}); const event=()=>svc.getActiveEvent(guildId); let msg='';
if(sub==='이벤트생성'){ const id=svc.createEvent({guildId,name:interaction.options.getString('이름',true),channelId:interaction.options.getChannel('채널',true).id,participantRoleId:interaction.options.getRole('참가역할')?.id,startingFund:interaction.options.getInteger('기본금')??15000}); msg=`청춘거래소 이벤트가 생성되었습니다. ID: ${id}`; }
else if(sub==='기본금지급'){ const e=event(); let users:string[]=[]; const type=interaction.options.getString('대상유형',true); if(type==='전체') users=svc.db.prepare('SELECT user_id FROM participants WHERE event_id=?').all(e.event_id).map((r:any)=>r.user_id); else if(type==='유저') users=[interaction.options.getUser('유저',true).id]; else { const role=interaction.options.getRole('역할',true); users=role.members?.filter((m:any)=>!m.user.bot).map((m:any)=>m.id)??[]; } const r=svc.grantStartingFund(e.event_id,uid,users,interaction.options.getInteger('금액')??e.starting_fund,interaction.options.getBoolean('중복허용')??false); msg=`신규 지급 ${r.paid}명, 제외 ${r.skipped}명, 1인 ${formatWon(r.amount)}, 총 ${formatWon(r.total)}`; }
else if(sub==='자금지급'){ const e=event(); const r=svc.grantAdminFund(e.event_id,uid,interaction.options.getUser('유저',true).id,interaction.options.getInteger('금액',true),interaction.options.getString('사유',true)); msg=`자금 지급 완료: ${formatWon(r.before)} → ${formatWon(r.after)}`; }
else if(sub==='아이템공개'||sub==='아이템비공개'){ const e=event(); svc.setItemPublic(e.event_id,uid,ids(interaction.options.getString('아이템id목록',true)),sub==='아이템공개'); msg='아이템 공개 상태를 변경했습니다.'; }
else if(sub==='구매시작'){ svc.startBuying(event().event_id); msg='구매를 시작했습니다.'; } else if(sub==='구매종료'){ svc.closeBuying(event().event_id); msg='구매를 종료했습니다.'; }
else if(sub==='구매'){ const r=svc.purchase(event().event_id,uid,interaction.options.getInteger('아이템id',true),interaction.options.getInteger('수량',true)); msg=`${r.item} ${r.qty}개 구매, 사용 ${formatWon(r.total)}, 잔액 ${formatWon(r.balance)}, 보유 ${r.itemQuantity}개`; }
else if(sub==='매입금설정'){ const e=event(); svc.setBuyout(e.event_id,uid,interaction.options.getInteger('아이템id',true),interaction.options.getInteger('매입금',true)); msg='매입금을 설정했습니다.'; }
else if(sub==='등급매입금설정'){ const e=event(); svc.setTierBuyout(e.event_id,uid,interaction.options.getString('등급',true),interaction.options.getInteger('매입금',true)); msg='등급 매입금을 설정했습니다.'; }
else if(sub==='매입금공개'){ const e=event(); svc.publishBuyouts(e.event_id,uid); msg='매입금을 공개했습니다. 지금부터 외부 계절 추첨을 진행하세요.'; }
else if(sub==='계절결과'){ const e=event(); svc.setSeason(e.event_id,uid,interaction.options.getString('계절',true)); msg=`외부 계절 결과: ${interaction.options.getString('계절',true)}`; }
else if(sub==='판매시작'){ const e=event(); const r=svc.startSelling(e.event_id,uid,{minutes:interaction.options.getInteger('분')??undefined,hhmm:interaction.options.getString('종료시각')??undefined}); msg=`판매 시작. 종료 시각: ${r.saleEnd}`; }
else if(sub==='판매종료'){ msg=svc.closeSelling(event().event_id)?'판매를 종료했습니다.':'이미 판매 종료 상태입니다.'; }
else if(sub==='판매신청'||sub==='판매변경'){ svc.saleRequest(event().event_id,uid,interaction.options.getInteger('아이템id',true),interaction.options.getInteger('수량',true)); msg='판매 신청을 저장했습니다.'; }
else if(sub==='판매취소'){ svc.cancelSale(event().event_id,uid,interaction.options.getInteger('아이템id',true)); msg='판매 신청을 취소했습니다.'; }
else if(sub==='정산미리보기'||sub==='판매현황'||sub==='매입금확인'){ const rows=svc.previewSettlement(event().event_id); msg=rows.map((r:any)=>`${r.name}: 신청 ${r.total_qty}개 / 단가 ${formatWon(r.unit_price)} / 지급 ${formatWon(r.total_paid)}`).join('\n')||'표시할 데이터가 없습니다.'; }
else if(sub==='정산'){ const rows=svc.settle(event().event_id,uid); msg='정산 완료\n'+rows.map((r:any)=>`${r.name}: ${r.total_qty}개, ${formatWon(r.unit_price)}`).join('\n'); }
else if(sub==='다음라운드'){ svc.nextRound(event().event_id,uid); msg='다음 라운드를 시작했습니다. 추가 구매 없이 매입금 설정 단계입니다.'; }
else if(sub==='이벤트종료'){ svc.endEvent(event().event_id,uid); msg='이벤트를 종료했고 남은 아이템은 환급 없이 소멸했습니다.'; }
else if(sub==='현황'){ const e=event(); const items=svc.db.prepare('SELECT name,price FROM items WHERE is_public=1').all().map((i:any)=>`${i.name} ${formatWon(i.price)}`).join(', '); msg=`이벤트 ${e.name}\n라운드 ${e.current_round}\n상태 ${e.status}\n공개 아이템: ${items||'없음'}\n계절 결과: ${e.selected_season??'미입력'}\n판매 종료: ${e.sale_end_at??'-'}`; }
else if(sub==='상점'){ msg=svc.db.prepare('SELECT item_id,name,season,price FROM items WHERE is_public=1').all().map((i:any)=>`${i.item_id}. [${i.season}] ${i.name} ${formatWon(i.price)}`).join('\n')||'공개된 아이템이 없습니다.'; }
else if(sub==='내정보'||sub==='내판매'||sub==='내역'||sub==='유저조회'||sub==='관리기록'){ const e=event(); const target=sub==='유저조회'?interaction.options.getUser('유저',true).id:uid; const p=svc.db.prepare('SELECT * FROM participants WHERE event_id=? AND user_id=?').get(e.event_id,target); const inv=svc.db.prepare('SELECT i.name,inv.quantity FROM inventories inv JOIN items i ON i.item_id=inv.item_id WHERE inv.event_id=? AND inv.user_id=? AND inv.quantity>0').all(e.event_id,target); msg=`잔액: ${formatWon(p?.balance??0)}\n보유: ${inv.map((x:any)=>`${x.name} ${x.quantity}개`).join(', ')||'없음'}`; }
return interaction.reply({content:msg,ephemeral: sub!=='현황'&&sub!=='상점'}); }catch(err:any){ console.error('[청춘거래소] 명령어 오류',{command:sub,message:err.message}); return interaction.reply({content:`오류: ${err.message}`,ephemeral:true}); }}
